kumuluzee:
  name: node-service
  server:
    base-url: http://localhost:3000
    http:
      port: 3000
  env:
    name: dev
  discovery:
    consul:
      hosts: http://localhost:8500
  config:
    consul:
      hosts: http://localhost:8500
rest-config:
  maintenance: false
